// src/routes/landing/Teaser.svelte
<script>
	import BaseComponent from '../components/BaseComponent.svelte';
</script>

<BaseComponent headline={'Teaser'} subHeadline={'A plant is not enough!'} id={'teaser'}>
	<div class="grid grid-cols-1 md:grid-cols-2">
		<div class="p-4">
			<iframe
				width="100%"
				height="315"
				src="https://www.youtube.com/embed/3D3N9r8PGv4"
				title="YouTube video player"
				frameborder="0"
				allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
				allowfullscreen
			/>
		</div>
		<div class="p-4">
			<div class="address lg:pl-24 flex flex-col">
				<p class="text-lg mb-2 text-left">
					Hackaburg 2023 has finally started! <br />Stay up to date over our social media channels.
				</p>
				<br />

				<div class="grid md:grid-cols-1 gap-4">
					<a
						href="https://www.instagram.com/hackaburg/"
						target="_blank"
						class="w-full max-w-xs text-md w-1/2 text-hackaburg border-2 border-hackaburg-900 text-hackaburg-900 rounded-3xl px-3 py-2 cursor-pointer hover:bg-hackaburg-900 hover:text-white flex flex-col items-center"
						>Follow us on Instagram</a
					>
					<a
						href="https://www.linkedin.com/company/17902166/"
						target="_blank"
						class="w-full max-w-xs text-md w-1/2 text-hackaburg border-2 border-hackaburg-900 text-hackaburg-900 rounded-3xl px-3 py-2 cursor-pointer hover:bg-hackaburg-900 hover:text-white flex flex-col items-center"
						>Follow us on LinkedIn</a
					>
				</div>
			</div>
		</div>
	</div>
</BaseComponent>

<style scoped>
	.venue {
		width: 100%;
		height: 25rem;
		border-radius: 5px;
	}
</style>

// src/components/teaser.tsx
import styled from "@emotion/styled";
import * as React from "react";
import { Anchors } from "../anchors";
import { breakpointMobile, breakpointTablet } from "../constants";
import { useScrollSpyMarker } from "../hooks/use-scrollspy";
import { Button } from "./button";
import { Column } from "./grid/column";
import { Row } from "./grid/row";
import { Header } from "./header";
import { Image } from "./image";
import { Link } from "./link";

const TeaserContainer = styled.section`
  position: relative;
`;

const AstronautContainer = styled.div`
  position: absolute;
  left: -7rem;
  top: 3rem;
  width: 30rem;

  @media screen and (max-width: ${breakpointTablet}) {
    display: none;
  }
`;

const Content = styled.div`
  position: relative;
  left: 13rem;
  margin: 10rem auto 20rem auto;
  width: 45rem;

  @media screen and (max-width: ${breakpointTablet}) {
    left: 0;
  }

  @media screen and (max-width: ${breakpointMobile}) {
    width: auto;
  }
`;

const Text = styled.p`
  font-size: 1rem;
  width: 21rem;

  @media screen and (max-width: ${breakpointMobile}) {
    width: auto;
  }
`;

const Spacer = styled.div`
  height: 2rem;
`;

const EmbeddedVideo = styled.iframe`
  width: 100%;
  height: 15rem;
  padding-left: 1rem;
  border-radius: 5px;

  @media screen and (max-width: ${breakpointMobile}) {
    padding: 1rem;
  }
`;

export const Teaser = () => {
  const marker = useScrollSpyMarker(Anchors.Teaser);
  return (
    <TeaserContainer>
      {marker}
      <AstronautContainer>
        <Image
          label="Astronaut with a computer"
          src="images/space/astronaut.png"
        />
      </AstronautContainer>
      <Content>
        <Header title="Teaser" subtitle="Launch sequence initiated" />
        <Spacer />
        <Row center>
          <Column width={1}>
            <Text>Hackaburg 2020 has finally started!</Text>
            <Text>Stay up to date on our social media channels</Text>

            <Link label="Hackaburg Instagram" target="_blank" to="">
              <Button fluid>Follow us on Instagram</Button>
            </Link>

            <br />

            <Link label="Hackaburg Facebook" target="_blank" to="">
              <Button fluid>Follow us on Facebook</Button>
            </Link>
          </Column>

          <Column width={30}>
            <EmbeddedVideo
              src="https://www.youtube.com/embed/OqN_HOEJLTA"
              frameBorder="0"
              allowFullScreen
            />
          </Column>
        </Row>
      </Content>
    </TeaserContainer>
  );
};
